server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:9090
          predicates:
            - Path=/v1/**
          filters:
            - RewritePath=/v1/(?<segment>.*), /$\{segment}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE