version: "3.9"
services:
  web:
    build: ./docker-flask
    ports:
      - "8080:5000"
    volumes:
      - ./docker-flask:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"